### ISSUE TITLE
登录后头像大了

### ISSUE THREAD

**Issue by wkivi9764** [Web3Camp-Labs/daopark#10]
## 问题描述
1、登录后头像大了改成44px试试
2、Hesder上边距小了下边距大了，期望上下居中
<img width="1584" alt="image" src="https://user-images.githubusercontent.com/114905537/202846399-aec51673-09aa-4138-94da-5c280849a7be.png">
<img width="1718" alt="image" src="https://user-images.githubusercontent.com/114905537/202846491-a7881951-eda6-401c-969d-8013c22a84ba.png">

## 期望结果
<img width="610" alt="image" src="https://user-images.githubusercontent.com/114905537/202846421-871bd436-0d52-4797-8d06-01cb2ae77121.png">

## 复现步骤
无
## 使用环境
- **设备/系统**: [e.g. Mac 16寸]
- **浏览器:** [e.g. chrome, safari]
- **钱包**: [e.g. Metamask]

## 优先级
Major
## 期望修复时间
2022.11/20

**Comment by wendychaung** [comment]
Fixed
