### ISSUE TITLE
下拉菜单样式问题

### ISSUE THREAD

**Issue by wkivi9764** [Web3Camp-Labs/daopark#11]
## 问题描述
1、边框描边粗了；
2、整体大了
3、字体有一丢丢小；
4、选项的间距需要上下居中
<img width="1697" alt="image" src="https://user-images.githubusercontent.com/114905537/202846612-27fdc73d-1025-47f4-817d-d882106a2775.png">
## 期望结果
<img width="965" alt="image" src="https://user-images.githubusercontent.com/114905537/202846686-3b1dd258-88fb-4db1-a0f0-32c02f800a5b.png">

## 复现步骤
无
## 使用环境
- **设备/系统**: [e.g. Mac 16寸]
- **浏览器:** [e.g. chrome, safari]
- **钱包**: [e.g. Metamask]

## 优先级
Major
## 期望修复时间
2022.11/20

**Comment by wendychaung** [comment]
Fixed
