### ISSUE TITLE
内容区整体宽了

### ISSUE THREAD

**Issue by wkivi9764** [Web3Camp-Labs/daopark#12]
## 问题描述
左右间距
<img width="1728" alt="image" src="https://user-images.githubusercontent.com/114905537/202847753-5eb2fd2a-df52-4f4d-8db3-aa34be5717b5.png">
按钮描边粗了
<img width="739" alt="image" src="https://user-images.githubusercontent.com/114905537/202847970-f4723be7-012b-4581-bce7-6da158087085.png">

## 期望结果
<img width="1716" alt="image" src="https://user-images.githubusercontent.com/114905537/202847801-da4982dd-59ee-4796-8e8b-b6e33925e470.png">

## 复现步骤
无
## 使用环境
- **设备/系统**: [e.g. Mac 16寸]
- **浏览器:** [e.g. chrome, safari]
- **钱包**: [e.g. Metamask]

## 优先级
Major
## 期望修复时间
2022.11/20

**Comment by wendychaung** [comment]
**Won't Fixed.** 
This part's  width is 1519px, if screen's width exceeds 1519px, this width will not changed. When this width is less than 1519px, this width will equal screen's width minus 2rem;
