### ISSUE TITLE
Add a DAO 页面按钮问题

### ISSUE THREAD

**Issue by wkivi9764** [Web3Camp-Labs/daopark#13]
## 问题描述
1、按钮样式不对，重新设计
2、Web3Camp Logo替换
<img width="1656" alt="image" src="https://user-images.githubusercontent.com/114905537/202848196-76483d15-79f8-48b4-90e4-b39c0eb67de6.png">
## 期望结果
<img width="172" alt="image" src="https://user-images.githubusercontent.com/114905537/202849870-3ab0bee8-800f-4edd-8aca-54d815fd3e0a.png">

## 复现步骤
无
## 使用环境
- **设备/系统**: [e.g. Mac 16寸]
- **浏览器:** [e.g. chrome, safari]
- **钱包**: [e.g. Metamask]

## 优先级
Major
## 期望修复时间
2022.11/20

**Comment by wendychaung** [comment]
Fixed
