### ISSUE TITLE
Logo没有悬停效果

### ISSUE THREAD

**Issue by wkivi9764** [Web3Camp-Labs/daopark#14]
## 问题描述
<img width="1717" alt="image" src="https://user-images.githubusercontent.com/114905537/202849963-c0214ccf-6849-4647-a4c0-90bda161bee8.png">
## 期望结果
悬停时应该为可点击状态
## 复现步骤
无
## 使用环境
- **设备/系统**: [e.g. Mac 16寸]
- **浏览器:** [e.g. chrome, safari]
- **钱包**: [e.g. Metamask]

## 优先级
Major
## 期望修复时间
2022.11/20

**Comment by wendychaung** [comment]
Fixed
