### ISSUE TITLE
红色部分描边跟绿色保持一致

### ISSUE THREAD

**Issue by wkivi9764** [Web3Camp-Labs/daopark#15]
## 问题描述
1、红色部分描边跟绿色保持一致
2、蓝色的认证标志靠上了
<img width="1697" alt="image" src="https://user-images.githubusercontent.com/114905537/202850301-2e1f1ba1-091d-477d-80e4-3a51f94a1e39.png">
## 复现步骤
无
## 使用环境
- **设备/系统**: [e.g. Mac 16寸]
- **浏览器:** [e.g. chrome, safari]
- **钱包**: [e.g. Metamask]

## 优先级
Major
## 期望修复时间
2022.11/20

**Comment by wendychaung** [comment]
Fixed
