### ISSUE TITLE
装饰元素显得大了

### ISSUE THREAD

**Issue by wkivi9764** [Web3Camp-Labs/daopark#16]
## 问题描述
1、红框内的描边太粗了
2、两个装饰元素缩小为现有尺寸的60%
<img width="1536" alt="image" src="https://user-images.githubusercontent.com/114905537/202850798-71d57528-1d27-455f-8e3e-a2107e79c60f.png">
## 复现步骤
无
## 使用环境
- **设备/系统**: [e.g. Mac 16寸]
- **浏览器:** [e.g. chrome, safari]
- **钱包**: [e.g. Metamask]

## 优先级
Major
## 期望修复时间
2022.11/20

**Comment by wendychaung** [comment]
Duplicated #19
