### ISSUE TITLE
卡片样式不对

### ISSUE THREAD

**Issue by wkivi9764** [Web3Camp-Labs/daopark#17]
## 问题描述

<img width="1523" alt="image" src="https://user-images.githubusercontent.com/114905537/202850978-8ed41c70-970e-4a73-a0fe-157d739a421e.png">
## 期望结果
<img width="362" alt="image" src="https://user-images.githubusercontent.com/114905537/202851082-7c707635-c453-479e-9d87-4569000233a0.png">

## 复现步骤
无
## 使用环境
- **设备/系统**: [e.g. Mac 16寸]
- **浏览器:** [e.g. chrome, safari]
- **钱包**: [e.g. Metamask]

## 优先级
Major
## 期望修复时间
2022.11/20

**Comment by wendychaung** [comment]
Fixed
