### ISSUE TITLE
元素替换

### ISSUE THREAD

**Issue by wkivi9764** [Web3Camp-Labs/daopark#19]
## 问题描述
1、红框内的元素大了
2、缺少缺省图，也需要比之前的尺寸小
<img width="1665" alt="image" src="https://user-images.githubusercontent.com/114905537/202851762-8117e0e6-0a16-4056-a6c6-bac4b49a6293.png">
## 期望结果
出新出了效果图，可以看下蓝湖
## 复现步骤https://share.lanhuapp.com/#/invite?sid=lxeOhD37
![image](https://user-images.githubusercontent.com/114905537/202851878-d798e631-e70f-48e4-a644-0dcff84df114.png)

无
## 使用环境
- **设备/系统**: [e.g. Mac 16寸]
- **浏览器:** [e.g. chrome, safari]
- **钱包**: [e.g. Metamask]

## 优先级
Major
## 期望修复时间
2022.11/20

**Comment by wendychaung** [comment]
Fixed
