### ISSUE TITLE
Add a DAO

### ISSUE THREAD

**Issue by wkivi9764** [Web3Camp-Labs/daopark#20]
## 问题描述
1、跳转有问题
2、按钮描边粗了
<img width="1693" alt="image" src="https://user-images.githubusercontent.com/114905537/202852335-d47af2af-de65-4fb0-b85a-b6847a21b1c8.png">

## 复现步骤
无
## 使用环境
- **设备/系统**: [e.g. Mac 16寸]
- **浏览器:** [e.g. chrome, safari]
- **钱包**: [e.g. Metamask]

## 优先级
Major
## 期望修复时间
2022.11/20

**Comment by wendychaung** [comment]
Fixed 2
