### ISSUE TITLE
无法上传LOGO和图片

### ISSUE THREAD

**Issue by wkivi9764** [Web3Camp-Labs/daopark#21]
## 问题描述
1、点击上传logo后不能上传图片
2、页面显示不正常
<img width="1506" alt="image" src="https://user-images.githubusercontent.com/114905537/202852394-4d92953e-ac53-44f4-a217-06be840c03c2.png">
<img width="1446" alt="image" src="https://user-images.githubusercontent.com/114905537/202852401-d2dfc588-3dcd-4bf6-9005-df0c6e8d0430.png">
<img width="1405" alt="image" src="https://user-images.githubusercontent.com/114905537/202852447-0163b77b-5f0a-44e2-a4d9-8d0726cb7b21.png">

## 期望结果
可以正常上传图片
## 复现步骤
点击Add a DAO,点击红框区域
<img width="1267" alt="image" src="https://user-images.githubusercontent.com/114905537/202852543-c203d23c-82e7-4826-ae0e-14f345210811.png">

## 使用环境
- **设备/系统**: [e.g. Mac 16寸]
- **浏览器:** [e.g. chrome]
- **钱包**: [e.g. Metamask]

## 优先级
Major
## 期望修复时间
2022.11/20

**Comment by wendychaung** [comment]
In this phase,we can't support image upload.If you wanna submit logo/cover ,you can paste your image url .In the future ,we will develop upload function.I was fixed the tips of image.
