### ISSUE TITLE
header高度和按钮样式问题

### ISSUE THREAD

**Issue by wkivi9764** [Web3Camp-Labs/daopark#6]
## 问题描述
1、Header高度高了
2、按钮样式和文字不对
<img width="1587" alt="image" src="https://user-images.githubusercontent.com/114905537/202845908-05d8ed48-2ef2-477d-b793-00807321827b.png">

## 期望结果
<img width="1708" alt="image" src="https://user-images.githubusercontent.com/114905537/202845932-3c7fa712-ae00-48c6-9832-7c0746e2df82.png">

## 复现步骤
无
## 使用环境
- **设备/系统**: [e.g. Mac 16寸]
- **浏览器:** [e.g. chrome, safari]
- **钱包**: [e.g. Metamask]

## 优先级
Major
## 期望修复时间
2022.11/20

**Comment by wendychaung** [comment]
Fixed
