### ISSUE TITLE
首页卡片背景不对

### ISSUE THREAD

**Issue by wkivi9764** [Web3Camp-Labs/daopark#8]
## 问题描述
网格背景左右不对称
<img width="488" alt="image" src="https://user-images.githubusercontent.com/114905537/202846243-d087dd17-6ed0-4729-b406-27ee67f8dcb2.png">

## 期望结果
<img width="388" alt="image" src="https://user-images.githubusercontent.com/114905537/202846252-2435bfe1-f38a-4308-8b0d-47218b3ce817.png">

## 复现步骤
无
## 使用环境
- **设备/系统**: [e.g. Mac 16寸]
- **浏览器:** [e.g. chrome, safari]
- **钱包**: [e.g. Metamask]

## 优先级
Major
## 期望修复时间
2022.11/20

**Comment by wendychaung** [comment]
设计如此

**Comment by wendychaung** [comment]
Fixed
