### ISSUE TITLE
web3Camplogo不是最新的

### ISSUE THREAD

**Issue by wkivi9764** [Web3Camp-Labs/daopark#9]
## 问题描述
Logo不是最新的
<img width="466" alt="image" src="https://user-images.githubusercontent.com/114905537/202846321-81aba048-1d14-4c98-b649-72dc55a8d304.png">

## 期望结果
<img width="150" alt="image" src="https://user-images.githubusercontent.com/114905537/202846337-888c3994-09d5-48ef-b64a-268ca0f5ec0b.png">

## 复现步骤
无
## 使用环境
- **设备/系统**: [e.g. Mac 16寸]
- **浏览器:** [e.g. chrome, safari]
- **钱包**: [e.g. Metamask]

## 优先级
Major
## 期望修复时间
2022.11/20

**Comment by wendychaung** [comment]
Fixed
